services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/notewise
    depends_on:
      - mongo

volumes:
  mongo_data:
