apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: notewise
  labels:
    app: notewise
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notewise
      tier: backend
  template:
    metadata:
      labels:
        app: notewise
        tier: backend
    spec:
      containers:
        - name: notewise-server
          image: notewise-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: notewise-secrets
                  key: MONGO_URI
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notewise-secrets
                  key: GROQ_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: notewise-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: notewise
  labels:
    app: notewise
    tier: backend
spec:
  selector:
    app: notewise
    tier: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
